import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import { FileText, Download, TrendingDown, Wallet, Users, UtensilsCrossed, AlertCircle, CheckCircle } from "lucide-react";
import {
  PageWrapper, PageHeader, Card, CardHeader, Button, Badge, Table, StatCard
} from "../components/ui";
import { formatCurrency } from "../utils/billing";

function BillRow({ member, currency }) {
  const isInDebt = member.due > 0;
  return (
    <div className="flex items-center gap-4 py-3 border-b border-gray-100 dark:border-white/6 last:border-0">
      <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-violet-500 to-indigo-500 flex items-center justify-center text-white text-sm font-bold flex-shrink-0">
        {(member.name || "?").charAt(0)}
      </div>
      <div className="flex-1 min-w-0">
        <p className="font-semibold text-sm text-gray-900 dark:text-white">{member.name}</p>
        <p className="text-xs text-gray-500 dark:text-gray-400">
          {member.meals?.toFixed(1)} meals · Rate: {formatCurrency(member.mealRate?.toFixed(2), currency)}
        </p>
      </div>
      <div className="text-right space-y-0.5">
        <p className="text-sm font-semibold text-gray-900 dark:text-white">{formatCurrency(member.total?.toFixed(2), currency)}</p>
        <p className={`text-xs font-medium ${isInDebt ? "text-red-500" : "text-green-500"}`}>
          {isInDebt ? `Due: ${formatCurrency(member.due?.toFixed(2), currency)}` : "Paid ✓"}
        </p>
      </div>
    </div>
  );
}

export function ReportsPage({ billData = {}, members = [], meals = [], bazaar = [], deposits = [], settings }) {
  const {
    memberBills = [], totalBazaar = 0, grandExpense = 0,
    totalMeals = 0, totalDeposits = 0, totalDue = 0, mealRate = 0,
  } = billData;

  const currency = settings?.currency || "৳";

  const month = new Date().toLocaleString("default", { month: "long", year: "numeric" });

  const paidMembers = memberBills.filter(m => m.due <= 0).length;
  const dueMembers  = memberBills.filter(m => m.due > 0).length;

  const sortedByDue = useMemo(() =>
    [...memberBills].sort((a, b) => b.due - a.due),
    [memberBills]
  );

  const handlePrintReport = () => {
    const content = `
MessManager - Monthly Report
${month}
${"=".repeat(40)}

SUMMARY
-------
Total Members:   ${members.length}
Total Meals:     ${totalMeals.toFixed(1)} units
Meal Rate:       ${formatCurrency(mealRate.toFixed(2), currency)} per unit
Total Bazaar:    ${formatCurrency(totalBazaar, currency)}
Total Deposits:  ${formatCurrency(totalDeposits, currency)}
Total Due:       ${formatCurrency(totalDue, currency)}

${"=".repeat(40)}
MEMBER BILLS
${"=".repeat(40)}
${memberBills.map(m =>
  `${m.name.padEnd(20)} Meals: ${m.meals.toFixed(1).padStart(5)}  Bill: ${formatCurrency(m.total.toFixed(2), currency).padStart(10)}  Deposit: ${formatCurrency(m.deposit.toFixed(2), currency).padStart(10)}  Due: ${formatCurrency(m.due.toFixed(2), currency).padStart(10)}`
).join("\n")}

${"=".repeat(40)}
BAZAAR ENTRIES
${"=".repeat(40)}
${bazaar.map(b =>
  `${(b.date || "").padEnd(12)} ${(b.title || "").padEnd(20)} ${formatCurrency(b.amount, currency).padStart(10)}`
).join("\n")}

Generated by MessManager Premium
${new Date().toLocaleString()}
    `;

    const blob = new Blob([content], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `mess-report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCSVExport = () => {
    const rows = [
      ["Name", "Meals", "Meal Cost", "Deposit", "Total Bill", "Due/Advance"],
      ...memberBills.map(m => [
        m.name, m.meals.toFixed(1),
        m.mealCost.toFixed(2), m.deposit.toFixed(2),
        m.total.toFixed(2), m.due.toFixed(2)
      ]),
    ];
    const csv = rows.map(r => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `member-bills-${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const tableColumns = [
    { key: "name", label: "Member" },
    { key: "meals", label: "Meals", render: (v) => v?.toFixed(1) },
    { key: "mealCost", label: "Meal Cost", render: (v) => formatCurrency(v?.toFixed(2), currency) },
    { key: "deposit",  label: "Deposit",   render: (v) => formatCurrency(v?.toFixed(2), currency) },
    { key: "total",    label: "Total Bill", render: (v) => <span className="font-semibold">{formatCurrency(v?.toFixed(2), currency)}</span> },
    {
      key: "due", label: "Status",
      render: (v, row) => (
        <div>
          {v > 0 ? (
            <Badge variant="danger">Due: {formatCurrency(v?.toFixed(2), currency)}</Badge>
          ) : (
            <Badge variant="success">+{formatCurrency(Math.abs(v)?.toFixed(2), currency)}</Badge>
          )}
        </div>
      )
    },
  ];

  return (
    <PageWrapper>
      <PageHeader
        title="Monthly Report"
        subtitle={month}
        actions={
          <div className="flex gap-2">
            <Button variant="secondary" onClick={handleCSVExport}>
              <Download size={16} /> CSV
            </Button>
            <Button onClick={handlePrintReport}>
              <FileText size={16} /> Export Report
            </Button>
          </div>
        }
      />

      {/* Summary stats */}
      <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-6 gap-4 mb-8">
        <StatCard label="Members" value={members.length} icon={Users} iconBg="bg-violet-500/10" iconColor="text-violet-500" />
        <StatCard label="Total Meals" value={totalMeals.toFixed(1)} icon={UtensilsCrossed} iconBg="bg-blue-500/10" iconColor="text-blue-500" />
        <StatCard label="Meal Rate" value={formatCurrency(mealRate.toFixed(2), currency)} icon={TrendingDown} iconBg="bg-orange-500/10" iconColor="text-orange-500" />
        <StatCard label="Total Bazaar" value={formatCurrency(totalBazaar, currency)} icon={TrendingDown} iconBg="bg-red-500/10" iconColor="text-red-500" />
        <StatCard label="Total Deposits" value={formatCurrency(totalDeposits, currency)} icon={Wallet} iconBg="bg-green-500/10" iconColor="text-green-500" />
        <StatCard label="Total Due" value={formatCurrency(totalDue, currency)} icon={AlertCircle} iconBg={totalDue > 0 ? "bg-red-500/10" : "bg-green-500/10"} iconColor={totalDue > 0 ? "text-red-500" : "text-green-500"} />
      </div>

      {/* Payment status summary */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        <Card className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-green-500/10 flex items-center justify-center">
            <CheckCircle size={20} className="text-green-500" />
          </div>
          <div>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{paidMembers}</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Settled / Advance</p>
          </div>
        </Card>
        <Card className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-red-500/10 flex items-center justify-center">
            <AlertCircle size={20} className="text-red-500" />
          </div>
          <div>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{dueMembers}</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Members with Due</p>
          </div>
        </Card>
      </div>

      {/* Bill table */}
      <Card noPad className="mb-6">
        <div className="p-6 pb-0">
          <CardHeader title="Member Bills" subtitle={`Calculated at ${formatCurrency(mealRate.toFixed(2), currency)}/meal unit`} />
        </div>
        <Table columns={tableColumns} data={sortedByDue} emptyState={
          <div className="p-12 text-center">
            <p className="text-sm text-gray-500 dark:text-gray-400">No bill data. Add members, meals, and bazaar entries first.</p>
          </div>
        } />
      </Card>

      {/* Calculation breakdown */}
      <Card>
        <CardHeader title="Calculation Breakdown" />
        <div className="space-y-3">
          {[
            { label: "Total Bazaar Expenses",    value: formatCurrency(totalBazaar, currency) },
            { label: "Total Meal Units Consumed", value: `${totalMeals.toFixed(2)} units` },
            { label: "Meal Rate",                value: `${formatCurrency(grandExpense || totalBazaar, currency)} ÷ ${totalMeals.toFixed(2)} = ${formatCurrency(mealRate.toFixed(4), currency)}/unit`, highlight: true },
          ].map(({ label, value, highlight }) => (
            <div key={label} className={`flex justify-between items-center p-3 rounded-xl ${highlight ? "bg-violet-50 dark:bg-violet-500/10 border border-violet-100 dark:border-violet-500/20" : "bg-gray-50 dark:bg-white/3"}`}>
              <p className={`text-sm ${highlight ? "font-semibold text-violet-700 dark:text-violet-300" : "text-gray-600 dark:text-gray-400"}`}>{label}</p>
              <p className={`text-sm font-bold ${highlight ? "text-violet-700 dark:text-violet-200" : "text-gray-900 dark:text-white"}`}>{value}</p>
            </div>
          ))}
        </div>

        <div className="mt-4 p-4 rounded-xl bg-gray-50 dark:bg-white/3 border border-gray-200 dark:border-white/8">
          <p className="text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase tracking-wide mb-2">Formula</p>
          <p className="text-sm font-mono text-gray-700 dark:text-gray-300">
            Member Bill = (Member Meals × Meal Rate) − Deposits
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
            Breakfast counts as 0.5 units · Lunch & Dinner count as 1 unit each
          </p>
        </div>
      </Card>
    </PageWrapper>
  );
}