export const MEAL_KEYS = ["breakfast", "lunch", "dinner"];

export const AUTO_MEAL_SOURCE = "permanent-auto";

export function getLocalDateKey(date = new Date()) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");

  return `${y}-${m}-${d}`;
}

export function getCurrentMonthKey(date = new Date()) {
  return getLocalDateKey(date).slice(0, 7);
}

export function getAutoMealId(ownerId, memberId, date = getLocalDateKey()) {
  return `auto_${ownerId}_${memberId}_${date}`;
}

export function getAutoMealSkipId(ownerId, memberId, date = getLocalDateKey()) {
  return `skip_${ownerId}_${memberId}_${date}`;
}

export function getSettingForMember(mealSettings = [], memberId) {
  return (
    mealSettings.find((setting) => setting.memberId === memberId) || {
      breakfast: false,
      lunch: false,
      dinner: false,
    }
  );
}

export function getEnabledMealKeys(setting = {}) {
  return MEAL_KEYS.filter((key) => Boolean(setting[key]));
}

export function countMealUnits(meal = {}) {
  return (
    Number(meal.breakfast || 0) * 0.5 +
    Number(meal.lunch || 0) +
    Number(meal.dinner || 0)
  );
}

export function isAutoPermanentMeal(meal = {}) {
  return meal.autoGenerated === true || meal.source === AUTO_MEAL_SOURCE;
}

export function getMealKeysWithValue(meal = {}) {
  return MEAL_KEYS.filter((key) => Number(meal[key] || 0) > 0);
}

export function getTodayAutoMealStats({
  meals = [],
  mealSettings = [],
  date = getLocalDateKey(),
} = {}) {
  const todayAutoMeals = meals.filter(
    (meal) => meal.date === date && isAutoPermanentMeal(meal)
  );

  return {
    entries: todayAutoMeals.length,
    units: todayAutoMeals.reduce((sum, meal) => sum + countMealUnits(meal), 0),
    membersEnabled: mealSettings.filter(
      (setting) => getEnabledMealKeys(setting).length > 0
    ).length,
  };
}

export function getAutoMealPreview({
  meals = [],
  mealSettings = [],
  memberId,
  date = getLocalDateKey(),
} = {}) {
  const setting = getSettingForMember(mealSettings, memberId);
  const enabled = getEnabledMealKeys(setting);
  const todayMeals = meals.filter(
    (meal) => meal.memberId === memberId && meal.date === date
  );
  const generated = todayMeals.filter(isAutoPermanentMeal);
  const overridden = todayMeals.some((meal) => meal.manualOverride);
  const present = MEAL_KEYS.filter((key) =>
    todayMeals.some((meal) => Number(meal[key] || 0) > 0)
  );

  return {
    enabled,
    generated,
    generatedKeys: MEAL_KEYS.filter((key) =>
      generated.some((meal) => Number(meal[key] || 0) > 0)
    ),
    present,
    overridden,
  };
}
