export const MEAL_KEYS = ["breakfast", "lunch", "dinner"];

export const AUTO_MEAL_SOURCE = "permanent-auto";

export function getLocalDateKey(date = new Date()) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");

  return `${y}-${m}-${d}`;
}

export function getCurrentMonthKey(date = new Date()) {
  return getLocalDateKey(date).slice(0, 7);
}

export function getAutoMealId(ownerId, memberId, date = getLocalDateKey()) {
  return `auto_${ownerId}_${memberId}_${date}`;
}

export function getAutoMealSkipId(ownerId, memberId, date = getLocalDateKey()) {
  return `skip_${ownerId}_${memberId}_${date}`;
}

export function getSettingForMember(mealSettings = [], memberId) {
  return (
    mealSettings.find((setting) => setting.memberId === memberId) || {
      breakfast: false,
      lunch: false,
      dinner: false,
    }
  );
}

export function getEnabledMealKeys(setting = {}) {
  const keys = [];
  if (resolveBreakfastMode(setting) !== "off") keys.push("breakfast");
  if (setting.lunch) keys.push("lunch");
  if (setting.dinner) keys.push("dinner");
  return keys;
}

export function countMealUnits(meal = {}) {
  return (
    Number(meal.breakfast || 0) * 0.5 +
    Number(meal.lunch || 0) +
    Number(meal.dinner || 0)
  );
}

export function isAutoPermanentMeal(meal = {}) {
  return meal.autoGenerated === true || meal.source === AUTO_MEAL_SOURCE;
}

export function getMealKeysWithValue(meal = {}) {
  return MEAL_KEYS.filter((key) => Number(meal[key] || 0) > 0);
}

export function getTodayAutoMealStats({
  meals = [],
  mealSettings = [],
  date = getLocalDateKey(),
} = {}) {
  const todayAutoMeals = meals.filter(
    (meal) => meal.date === date && isAutoPermanentMeal(meal)
  );

  return {
    entries: todayAutoMeals.length,
    units: todayAutoMeals.reduce((sum, meal) => sum + countMealUnits(meal), 0),
    membersEnabled: mealSettings.filter(
      (setting) => getEnabledMealKeys(setting).length > 0
    ).length,
  };
}

export function getAutoMealPreview({
  meals = [],
  mealSettings = [],
  memberId,
  date = getLocalDateKey(),
} = {}) {
  const setting = getSettingForMember(mealSettings, memberId);
  const enabled = getEnabledMealKeys(setting);
  const todayMeals = meals.filter(
    (meal) => meal.memberId === memberId && meal.date === date
  );
  const generated = todayMeals.filter(isAutoPermanentMeal);
  const overridden = todayMeals.some((meal) => meal.manualOverride);
  const present = MEAL_KEYS.filter((key) =>
    todayMeals.some((meal) => Number(meal[key] || 0) > 0)
  );

  return {
    enabled,
    generated,
    generatedKeys: MEAL_KEYS.filter((key) =>
      generated.some((meal) => Number(meal[key] || 0) > 0)
    ),
    present,
    overridden,
  };
}

// --- Breakfast Mode Utilities ---

export const BREAKFAST_MODES = { OFF: "off", HALF: "half", FULL: "full" };

/**
 * Resolves the breakfast mode from a meal setting document.
 * Uses the `breakfastMode` field if valid, otherwise falls back to legacy `breakfast` boolean.
 * @param {object} setting - A meal setting document
 * @returns {"off" | "half" | "full"}
 */
export function resolveBreakfastMode(setting = {}) {
  if (
    setting.breakfastMode &&
    ["off", "half", "full"].includes(setting.breakfastMode)
  ) {
    return setting.breakfastMode;
  }
  return setting.breakfast ? "half" : "off";
}

/**
 * Returns the next breakfast mode in the cycle: off → half → full → off.
 * Defaults to "half" for unknown input.
 * @param {string} current - The current breakfast mode
 * @returns {"off" | "half" | "full"}
 */
export function getNextBreakfastMode(current) {
  const CYCLE = { off: "half", half: "full", full: "off" };
  return CYCLE[current] || "half";
}

/**
 * Maps a breakfast mode to its raw integer value for storage in meal documents.
 * The raw value × 0.5 gives the actual meal units.
 * @param {string} mode - The breakfast mode ("off", "half", or "full")
 * @returns {number} 0, 1, or 2
 */
export function getBreakfastRawValue(mode) {
  const RAW = { off: 0, half: 1, full: 2 };
  return RAW[mode] ?? 0;
}
